---
title: "Nomura 2020, Ayush Agarwal" 
author: "Explainers"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output:
  prettydoc::html_pretty:
    keep_md: True
    theme: cayman
    highlight: github
---


## Contact Information :
***
**Email**          : ayush.agarwal2@nomura.com, ayuag@iitk.ac.in  
**GitHub handle**  : [ayushmclaren](http://github.com/ayushmclaren)  
**Telephone**      : +91 9815139259 \\
**Whatsapp**       : +91 9872548037

# Day 1

## Q1 : Explain the move in oil.

First of all, the markets are flooded with oil. Since the pandemic started, an estimated 30% of the world demand has perished while the output has majorly remained the same. Around April 13, Oil deal was announced. However, the cuts were much lower than expected and if you look closely within you’ll find it really isn’t as goody good as it sounds. Russia’s output has not fallen in years and it will continue to violate OPEC+ deals as it had been all this while, and the 2.5 mn cut Saudi announced was from a 11 mn baseline which it has never been able to sustain daily anyway, it’s average is around 8.5 which means the remains 2.5 was coming from inventories anyway. To sum it up, Oil deal failed to inspire confidence and offer the much needed respite. Now, Oil is traded in Futures contract, and WTI in particular is a physically settled futures contract. Most of the trade is a speculative one, therefore do not want physical oil, and refiners given the glut, no demand, tough transport conditions don’t want it either. Now, most of the WTI oil is delivered at Cushing, Oklahoma where you have to take delivery of the oil. Since the forward month was May, delivery was to be taken between 1st to 31st or else pay them to store. Some oil producers even want to induce Force Majeure. With this comes the expiry date for May’s contract, April 20th. Removing oil would be impossible cause after all its 1000 barrels per contract. Even Cushing is dangerously close to it’s capacity and is left with 2 weeks of capacity, and due to the dynamic nature of pricing the storage cost is now disproportionately high. Even the offshore containers near the African coast are not available. So much so that companies have now asked permissions to convert pipelines into temporary storage. The realisation hits the market and about 3 hours before expiry oil is dangerously flirting near \$0 levels. Panic starts to seep in, and within minutes we see oil has gone below 0\$. Anyone rolling over would have to pay as much as $60 (since when at -40 levels, June forwards were still trading at \$20). Hence people figured it’s better to pay someone to get rid of the oil contacts instead of the alternatives. 
